---
- name: Ініціалізація Kubernetes кластеру
  hosts: masters
  become: yes

  tasks:
    - name: Ініціалізація кластеру
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Скопіювати конфігураційний файл для користувача
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
