---
- hosts: all
  become: yes
  tasks:
    - name: Ensure old k3s installation is removed
      shell: /usr/local/bin/k3s-uninstall.sh || true
      ignore_errors: yes

    - name: Download and install k3s
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
      register: k3s_install

    - name: Verify if k3s is installed as a server
      stat:
        path: /var/lib/rancher/k3s/server/node-token
      register: server_token_exists

    - name: Get the server node token
      shell: "cat /var/lib/rancher/k3s/server/node-token"
      register: server_node_token
      when: server_token_exists.stat.exists
      changed_when: false

    - name: Save server node token for worker nodes
      copy:
        content: "{{ server_node_token.stdout }}"
        dest: /tmp/server_node_token.txt
      when: server_token_exists.stat.exists

    - name: Display the server node token
      debug:
        msg: "K3s Server Node Token: {{ server_node_token.stdout }}"
      when: server_token_exists.stat.exists

